---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    dnf:
      update_cache: yes
    when: ansible_distribution == "Red Hat Enterprise Linux"

  - name: install apache package
    yum:
      name: httpd
      state: latest
    when: ansible_distribution == "Red Hat Enterprise Linux"

  - name: add php support for apache
    yum:
      name: php
      state: latest
    when: ansible_distribution == "Red Hat Enterprise Linux"
...

